---
- name: Install TensorFlow
  environment:
    PATH: "{{ home }}/.local/bin"
  pip:
    name: tensorflow
    virtualenv: "{{ home }}/keras_env"

- name: Install Keras
  environment:
    PATH: "{{ home }}/.local/bin"
  pip:
    name: keras
    virtualenv: "{{ home }}/keras_env"
